# Generated by Django 5.2.5 on 2025-08-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_transaction_receiver_email_transaction_receiver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receiver_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver_name',
            field=models.CharField(),
        ),
    ]
