# Generated by Django 5.2.5 on 2025-08-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_transaction_receiver_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receiver_email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver_name',
            field=models.CharField(default='Unknown'),
        ),
    ]
