# Generated by Django 5.2.5 on 2025-08-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_transaction_receiver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receiver_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
